#!/bin/bash
set -e

export DB_HOST=mysql
export DB_NAME=shiftworkweb
export DB_USER=`cat /etc/secret/username`
export DB_PASSWORD=`cat /etc/secret/password`


# Apache gets grumpy about PID files pre-existing
rm -f /var/run/apache2/apache2.pid

exec apache2 -DFOREGROUND
